In [8]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
list_,array_list

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


(['1', '2', '3', '4', '5'], array(['1', '2', '3', '4', '5'], dtype='<U1'))

In [9]:
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [13]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [14]:
zeros_matrix = np.zeros((3, 3))

print("3x3 matrix of zeros:")
print(zeros_matrix)

3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
